import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import GoogleProvider from "./(providers)/GoogleProvider";
import { CartProvider } from "./context/CartContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chipe/Libros",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Aqui se recomienda establecer las rutas */}
        <AppRouterCacheProvider>
        <GoogleProvider>
          <CartProvider>
          {children}
          </CartProvider>
          </GoogleProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
